version: 2
jobs:
  test:
    macos:
      xcode: "10.2.0"
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      - run:
          name: Run tests
          command: swift test

workflows:
  version: 2
  build-test-lint:
    jobs:
      - test
