name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      env: 
        DEVELOPER_DIR: /Applications/Xcode_14.0.1.app
      run: swift test
