name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      env: 
        DEVELOPER_DIR: /Applications/Xcode_10.2.1.app
      run: swift test
