name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: macOS-10.15
    steps:
    - uses: actions/checkout@v2.3.1
    - name: Run tests
      env: 
        DEVELOPER_DIR: /Applications/Xcode_11.4.app
      run: swift test
